const ContactListTypes={
    GET_CONTACT_LIST:"GET_CONTACT_LIST",
    GET_CONTACT_LIST_SUCCESS:"GET_CONTACT_LIST_SUCCESS",
    GET_CONTACT_LIST_FAILURE:"GET_CONTACT_LIST_FAILURE",
    RESET_CONTACT_LIST:"RESET_CONTACT_LIST"

}

export default ContactListTypes
