const ContactListTypes={
    GET_CONTACT_LIST:"GET_CONTACT_LIST",
    GET_CONTACT_LIST_SUCCESS:"GET_CONTACT_LIST_SUCCESS",
    GET_CONTACT_LIST_FAILURE:"GET_CONTACT_LIST_FAILURE"
}

export default ContactListTypes
